### ISSUE TITLE
Is there code opend to the public?

### ISSUE THREAD

**Issue by cvjimmy0704** [paschalidoud/hierarchical_primitives#2]
Hi, thank you for this very interesting work. I wonder if there is released code and/or pretrained model opened to the public? Thank you.

**Comment by paschalidoud** [comment]
Hi,

I am working towards releasing the code as well as the pretrained models within the next few days. I am happy to let you know as soon as the code is out.

Cheers,
Despoina

**Comment by amiltonwong** [comment]
Hi, @paschalidoud , 
Any updates on the release?

**Comment by paschalidoud** [comment]
Hi @amiltonwong,

Thanks a lot for your interest. Code and data will be available very soon :-)

Best,
Despoina

**Comment by rose-jinyang** [comment]
Hi
How are you?
Where can I find the source code?
I hope that u will share the source code asap.
Thank you.

**Comment by wanghanxiao123** [comment]
Hi @paschalidoud 
How are you?
We are interested in your work ,
Looking forward for your code
Thank you : )

**Comment by amiltonwong** [comment]
Hi, @paschalidoud ,

Any update news on the code release?

THX!

**Comment by paschalidoud** [comment]
Hi all,

I am really sorry for taking so long to release the code. The code together with the corresponding scripts for training and evaluation are available. 

I am closing the issue for now. Please let me know if something is not clear. I will update the README with concrete guidelines for running the provided scripts.

Best,
Despoina
