### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by qiminchen** [paschalidoud/hierarchical_primitives#3]
Hi, thanks for the amazing work! I'm wondering when the training code would be available? And trained model if possible.

**Comment by paschalidoud** [comment]
Hi @qiminchen 

I am really sorry for taking so long to reply and to release the code. The code is finally available together with the corresponding scripts for training and testing.

I will close the issue for now. Please let me now if you have any problem or if something is not clear.

Best,
Despoina
