### ISSUE TITLE
Missing function 'check_mesh_contains'

### ISSUE THREAD

**Issue by bmlklwx** [paschalidoud/hierarchical_primitives#5]
Good job! 
While, in generate_surface_samples.py, I found out that the following function
```python
from learnable_primitives.external.libmesh import check_mesh_contains
```
might be missing. I am wondering if you could upload when convenience.
Also, if I understand correctly, the `learnable_primitives` in
```python
from learnable_primitives.common.model_factory import DatasetBuilder
from learnable_primitives.common.base import splits_factory
from learnable_primitives.external.libmesh import check_mesh_contains
from learnable_primitives.mesh import Trimesh
from learnable_primitives.utils.progbar import Progbar
```
should be `hierarchical_primitives`?

**Comment by paschalidoud** [comment]
Hi @bmlklwx,

You are right libmesh was missing completely. I just committed it, so the issue should be resolved. To check whether a 3D point lies inside or outside a mesh, we use the code from https://github.com/autonomousvision/occupancy_networks/tree/ddb2908f96de9c0c5a30c093f2a701878ffc1f4a/im2mesh/utils/libmesh.

I also fixed the wrong import in the generate_surface_samples.py script! I am sorry for the trouble!

I am closing the issue for now, but please feel free to reopen it in case you my fix doesn't work.

Best,
Despoina
